[package]
name = "ark-invest-api-rust-data"
version = "0.1.0"
edition = "2021"

[dependencies]
polars = { version = "0.30", features = [
	"lazy",
	"strings",
	"parquet",
	"round_series",
	"lazy_regex",
	"json",
	"object",
	"dtype-struct",
] }
reqwest = { version = "0.11", features = ["blocking"] }
glob = { version = "0.3" }
clokwerk = "0.4.0"
strum_macros = "0.24"
strum = "0.24"
tokio = { version = "1.26", features = ["full"] }
openssl = { version = "0.10", features = ["vendored"] }
chrono = { version = "0.4", features = ["serde"] }
serde_json = "1.0"

[dev-dependencies]
serial_test = "*"
