[package]
name = "ark-invest-api-rust-data"
version = "1.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
polars = { version = "0.32", features = [
	"lazy",
	"strings",
	"parquet",
	"round_series",
	"lazy_regex",
	"json",
	"object",
	"dtype-struct",
] }
reqwest = { version = "0.11", features = ["blocking", "gzip"] }
glob = { version = "0.3" }
clokwerk = "0.4"
strum_macros = "0.25"
strum = "0.25"
tokio = { version = "1.34", features = ["full"] }
openssl = { version = "0.10", features = ["vendored"] }
chrono = { version = "0.4", features = ["serde"] }
serde_json = "1.0"
rand = "0.8"
futures = "0.3"
lazy_static = "1.4"
anyhow = "1.0"

[dev-dependencies]
serial_test = "*"
