version: "3"
services:
    ark-invest-api-rust-data-test:
        container_name: ark-invest-api-rust-data-test
        build:
            context: .
            target: test
            args:
                DOCKER_BUILDKIT: 1
        restart: no

    ark-invest-api-rust-data:
        # image: ghcr.io/NexVeridian/ark-invest-api-rust-data:latest
        image: ark-invest-api-rust-data
        container_name: ark-invest-api-rust-data
        build:
            context: .
            target: main
            args:
                DOCKER_BUILDKIT: 1
        restart: no
        environment:
            - ARK_SOURCE=ARK
            # - STARTUP_CSV_MERGE=true
            # - STARTUP_ARK_ETF=true
        volumes:
            - ./data:/ark-invest-api-rust-data/data

volumes:
    data: