# [target.x86_64-unknown-linux-gnu]
# linker = "clang"
# rustflags = ["-C", "link-arg=-fuse-ld=/usr/bin/mold"]

[alias]
t = "nextest run"

[build]
target-dir = "target/target"

[unstable]
codegen-backend = true

[profile.release]
codegen-backend = "cranelift"

[profile.dev]
codegen-backend = "cranelift"
